/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class danilo_jovanovic_shoppinglist_JNIExample */

#ifndef _Included_danilo_jovanovic_shoppinglist_JNIExample
#define _Included_danilo_jovanovic_shoppinglist_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     danilo_jovanovic_shoppinglist_JNIExample
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_danilo_jovanovic_shoppinglist_JNIExample_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
